spring:
  # 数据源相关配置
  datasource:
    url: jdbc:p6spy:mysql://yangxuchen.com:3306/xxgc_test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: yxc132528
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver  # com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
    data-format: yyyy-MM-dd HH:mm:ss

# 日志相关配置
logging:
  level:
    com.xgkx: debug

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml  # 设置mapper路径
  typeAliasesPackage: com.xgkx.procurement.entity   # 设置实体类所在包
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      column-underline: true  # 驼峰下划线转换
#      logic-delete-value: 0  # 逻辑删除配置  删除的值为0
#      logic-not-delete-value: 1   # 逻辑删除配置  不删除的值为1
      db-type: mysql
    refresh: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    # 不打印sql
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

# 配置pageHelper分页插件的内容
pagehelper:
  helperDialect: mysql
  # 分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页，
  # pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询。
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


# seagger信息配置
swagger:
  auth: 杨旭晨
  url: http://api.yangxuchen.com
  authEmail: yangxuchen@yangxuchen.com
  title: 采购系统api
  description: 采购管理系统api
  version: 0.0.1

# jwt相关配置
jwt:
  # 签名
  signature: yangxuchenkey
  # 过期时间  单位 s
  exp: 604800  # 7 * 60 * 60 * 24

# 文件目录
file:
  exportTemplateFilePath: c:\\data\\procurement

